CREATE TABLE TINH_TP(
 MA_T_TP VARCHAR(3) PRIMARY KEY,
 TEN_T_TP NVARCHAR(20) NOT NULL,
 DT FLOAT ,
 DS BIGINT,
 MIEN NVARCHAR(10) NOT NULL
 );
 CREATE TABLE BIENGIOI(
 NUOC NVARCHAR(15),
 MA_T_TP VARCHAR(3),
 FOREIGN KEY (MA_T_TP) REFERENCES TINH_TP(MA_T_TP)
 );
 CREATE TABLE LANGGIENG(
 MA_T_TP VARCHAR(3) NOT NULL,
 FOREIGN KEY(MA_T_TP) REFERENCES TINH_TP(MA_T_TP),
 LG VARCHAR(3) NOT NULL,
 FOREIGN KEY(LG) REFERENCES TINH_TP(MA_T_TP)
 );
